### ISSUE TITLE
Quick note on Overledger docs

### ISSUE THREAD

**Issue by SamdevQ** [quantnetwork/overledger-sdk-javascript-v2#35]
Hey all, hope this is helpful.

Just noticed the docs' (https://docs.overledger.io/) "Try It" example boxes point to an (invalid) placeholder url, `https://ovl 2.0/`. I wasn't sure where else to report this, I hope this is an okay place to post.

I wanted to play with some of the endpoints when perusing the docs, but sadly this is a blocker.

In addition, the docs linked to in the README of this project, https://api.sandbox.overledger.io/v2/documentation/swagger-ui.html, seem to not be working. I just see the following:

> 😱 Could not render e, see the console.

I'm guessing it is because the network request to https://api.sandbox.overledger.io/v2/documentation/ comes back with a 401, but not completely sure.

**Comment by lukerQuant** [comment]
As regards your other issue @SamdevQ the openAPI3 docs pointing to the different environments can be found here: https://github.com/quantnetwork/overledger-sdks/tree/main/overledger-openAPI3 . Therefore I am closing this issue
